# -*- coding: utf-8 -*-
"""Task-3 Customer Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ts1gkW8qpoUoaFxAWv5h5M1JaPmVi81m

# **Task-3 Customer Segmentation**

# 1. Load and Clean the Dataset


```
1.1 Import Libraries
1.2 Data From GitHub
1.3 Display First 5 rows
1.4 Dataset Information
1.5 Check the missing values
1.6 Convert TotalCharges to Numeric
1.7 Fill the missing value with median
1.8 Also Check the " " value
1.9 Convert types
```
"""

# 1.1 Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 1.2 Data From GitHub

# GitHub raw URL
url = 'https://raw.githubusercontent.com/abuthahir17/Dataset/main/Telco_Customer_Churn_Dataset.csv'

# Read CSV file
data = pd.read_csv(url)

print("Dataset Loaded Successfully!")

# 1.3 Display First 5 rows
print("First Five Rows in the Dataset: \n")
data.head()

# 1.4 Dataset Information
print("Dataset Info:\n")
print(data.info())

# 1.5 Check the missing values
data.replace(" ", None, inplace=True)
print("Missing Value: \n", data.isnull().sum())

# 1.6 Convert TotalCharges to Numeric
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")

# 1.7 Fill the missing value with median
data["TotalCharges"] = data["TotalCharges"].fillna(data["TotalCharges"].median())

# 1.8 Also Check the " " value
data.replace(" ", None, inplace=True)
print("Missing Value after Cleaning: \n", data.isnull().sum())

# 1.9 Convert types
data["Churn"] = data["Churn"].map({"Yes":1, "No":0})

"""# 2. Create Segments


```
2.1 Tenure Segments
2.2 Monthly Charges Segments
```


"""

# 2.1 Tenure Segments
data["Tenure_Group"] = pd.cut(
    data["tenure"],
    bins=[0, 12, 36, 72],
    labels=["0-1 Year", "1-3 Years", "3-6 Years"]
)

# 2.2 Monthly Charges Segments
data["MonthlyCharges_Group"] = pd.cut(
    data["MonthlyCharges"],
    bins=[0, 35, 70, 120],
    labels=["Low", "Medium", "High"]
)

"""# 3. Churn Rate Analysis by Segments



```
3.1 Churn by Tenure
3.2 Churn by Monthly Charges
3.3 Churn by Contract Type
```


"""

# 3.1 Churn by Tenure
tenure_churn = data.groupby("Tenure_Group")["Churn"].mean()*100
print("Churn Rate by Tenure Group:\n\n", tenure_churn)

# 3.2 Churn by Monthly Charges
mcharges_churn = data.groupby("MonthlyCharges_Group")["Churn"].mean()*100
print("Churn Rate by Monthly Charges:\n\n", mcharges_churn)

# 3.3 Churn by Contract Type
contract_churn = data.groupby("Contract")["Churn"].mean()*100
print("Churn Rate by Contract Type:\n\n", contract_churn)

"""# 4. Visualizations



```
4.1 Tenure vs Churn
4.2 Monthly Charges vs Churn
4.3 Contract Type vs Churn
4.4 Heatmap for Correlation
```


"""

# 4.1 Tenure vs Churn
plt.figure(figsize=(7,5))
sns.barplot(x=tenure_churn.index, y=tenure_churn.values)
plt.title("Churn Rate by Tenure Segment (%)")
plt.ylabel("Churn %")
plt.show()

# 4.2 Monthly Charges vs Churn
plt.figure(figsize=(7,5))
sns.barplot(x=mcharges_churn.index, y=mcharges_churn.values)
plt.title("Churn Rate by Monthly Charges Segment (%)")
plt.ylabel("Churn %")
plt.show()

# 4.3 Contract Type vs Churn
plt.figure(figsize=(7,5))
sns.barplot(x=contract_churn.index, y=contract_churn.values)
plt.title("Churn Rate by Contract Type (%)")
plt.ylabel("Churn %")
plt.show()

# 4.4 Heatmap for Correlation

# Select only numeric columns
numeric_data = data.select_dtypes(include=["int64", "float64"])

# Heatmap
plt.figure(figsize=(10,6))
sns.heatmap(numeric_data.corr(), cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

"""# 5. Segment-wise Churn Rate Pivot Table


```
5.1 Churn Rate Pivot Table
```


"""

# 5.1 Churn Rate Pivot Table
pivot = pd.pivot_table(
    data,
    values="Churn",
    index="Tenure_Group",
    columns="Contract",
    aggfunc="mean"
) * 100

print(pivot.round(2))

"""# 6. High-Value Customer Churn Risk Identification


```
6.1 Create Risk Score
6.2 High-value churn-risk customers
6.3 Count of High-Value Churn-Risk Customers
```


"""

# 6.1 Create Risk Score
data["Churn_Risk_Score"] = (
    (data["MonthlyCharges"] / data["MonthlyCharges"].max()) * 40 +
    (data["tenure"] / data["tenure"].max()) * 20 +
    data["Churn"] * 40
).round(2)

data[["customerID", "MonthlyCharges", "tenure", "Churn_Risk_Score"]].head()

# 6.2 High-value churn-risk customers
high_value_risk = data[
    (data["MonthlyCharges"] > 70) &
    (data["tenure"] > 12) &
    (data["Churn_Risk_Score"] > 60)
]

high_value_risk.head()

# 6.3 Count of High-Value Churn-Risk Customers
print("High-value customers at risk of churn:", len(high_value_risk))

"""# 7. Customer Segmentation using K-Means



```
7.1 Preparing Data and Creating K-Means Clusters
7.2 Visualizing Customer Clusters
```


"""

# 7.1 Preparing Data and Creating K-Means Clusters

cluster_data = data[["tenure", "MonthlyCharges", "TotalCharges"]]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(cluster_data)

kmeans = KMeans(n_clusters=4, random_state=42)
data["Cluster"] = kmeans.fit_predict(scaled_data)

data.groupby("Cluster")[["tenure", "MonthlyCharges"]].mean()

# 7.2 Visualizing Customer Clusters

plt.figure(figsize=(8,6))
sns.scatterplot(
    x=data["tenure"],
    y=data["MonthlyCharges"],
    hue=data["Cluster"],
    palette="tab10"
)
plt.title("Customer Segmentation using K-Means")
plt.show()

"""# 8. Final Summary Table for All Segments


```
8.1 Report Generating
8.2 Download Final Summary Report (CSV)
```


"""

# 8.1 Report Generating

final_report = data.groupby(
    ["Cluster", "Tenure_Group", "MonthlyCharges_Group", "Contract"]
).agg(
    Customers=("customerID", "count"),
    Avg_Tenure=("tenure", "mean"),
    Avg_Charges=("MonthlyCharges", "mean"),
    Churn_Rate=("Churn", "mean"),
    High_Risk=("Churn_Risk_Score", lambda x: (x > 70).sum())
).round(2)

print("\nFinal Summary Report:\n")
final_report

# 8.2 Download Final Summary Report (CSV)
from google.colab import files
final_report.to_csv("Task3_Final_Report.csv", index=True)
files.download("Task3_Final_Report.csv")