# -*- coding: utf-8 -*-
"""Task-2 Exploratory Data Analysis (EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O2WZl4cQ2zDi3XMKYYjyY21W6FYbgZ_U

# **TASK 2 — Exploratory Data Analysis (EDA)**

# 1. Loading the Dataset

```
1.1 Data From GitHub
1.2 Display First 5 Rows
1.3 Dataset Information
```
"""

# 1.1 Data From GitHub

import pandas as pd

# GitHub raw URL
url = 'https://raw.githubusercontent.com/abuthahir17/Dataset/main/Telco_Customer_Churn_Dataset.csv'

# Read CSV file
data = pd.read_csv(url)

print("Dataset Loaded Successfully!")

# 1.2 Display First 5 rows
print("First Five Rows in the Dataset: \n")
data.head()

# 1.3 Dataset Information
print("\nDataset Info:\n")
print(data.info())

"""# 2. Handling Missing Values


```
2.1 Check the missing values
2.2 TotalCharges -> Numeric (Convert)
2.3 Fill with Median
2.4 Recheck Null (missing) values
```


"""

# 2.1 Check the missing values
data.replace(" ", None, inplace=True)
print("Missing Value: \n", data.isnull().sum())

# 2.2 Convert TotalCharges to Numeric
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")

# 2.3 Fill the missing value with median
data["TotalCharges"] = data["TotalCharges"].fillna(data["TotalCharges"].median())

# 2.4 Also Check the " " value
data.replace(" ", None, inplace=True)
print("Missing Value after Cleaning: \n", data.isnull().sum())

"""# 3. Calculate and visually represent the overall churn rate



```
3.1 Calculation for churn rate
3.2 Visual Representation
```


"""

# 3.1 Calculate churn rate
churn_rate = data['Churn'].value_counts(normalize=True) * 100
print("Overall Churn Rate in Percentage:")
print(churn_rate)

# 3.2 Visual Representation for churn distribution Rate

import matplotlib.pyplot as plt

plt.figure()
data['Churn'].value_counts().plot(kind='bar')
plt.title("Churn Distribution Rate" )
plt.xlabel("Churn")
plt.ylabel("Count")
plt.show()

"""# 4. Explore customer distribution by gender, partner status, and dependent status.



```
4.1 Gender vs Churn
4.2 Partner Status vs Churn
4.3 Dependent Status vs Churn
```




"""

# 4.1 Gender vs Churn

# Plot the Graph

import seaborn as sns
plt.figure()
sns.countplot(data=data, x="gender", hue="Churn")
plt.title("Customer Distribution by Gender and Churn")
plt.xlabel("Gender")
plt.ylabel("Count")
plt.tight_layout()
plt.show()


# Gender_Churn_Rate
gender_churn = (
    data.groupby("gender")["Churn"]
    .value_counts(normalize=True)
    .unstack() * 100
).rename(columns={"Yes": "Churn_Yes", "No": "Churn_No"})

gender_churn.round(2)

# 4.2 Partner Status vs Churn

# Plot the Graph
plt.figure()
sns.countplot(data=data, x="Partner", hue="Churn")
plt.title("Customer Distribution by Partner Status and Churn")
plt.xlabel("Partner")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# Partner_Churn_Rate
partner_churn = (
    data.groupby("Partner")["Churn"]
    .value_counts(normalize=True)
    .unstack() * 100
).rename(columns={"Yes": "Churn_Yes", "No": "Churn_No"})

partner_churn.round(2)

# 4.3 Dependent Status vs Churn

# Plot the Graph
plt.figure()
sns.countplot(data=data, x="Dependents", hue="Churn")
plt.title("Customer Distribution by Dependents and Churn")
plt.xlabel("Dependents")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# Dependents_Churn_Rate
dependents_churn = (
    data.groupby("Dependents")["Churn"]
    .value_counts(normalize=True)
    .unstack() * 100
).rename(columns={"Yes": "Churn_Yes", "No": "Churn_No"})

dependents_churn.round(2)

"""# 5. Analyze Tenure distribution and its relation with churn.



```
5.1 Overall tenure distribution
5.2 Tenure distribution split by churn
5.3 Boxplot – tenure vs churn
5.4 Summary statistics – tenure by churn
```



"""

# 5.1 Overall tenure distribution
plt.figure()
sns.histplot(data["tenure"], bins=30, kde=True)
plt.title("Tenure Distribution (All Customers)")
plt.xlabel("Tenure (months)")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# 5.2 Tenure distribution split by churn
plt.figure()
sns.histplot(data=data, x="tenure", hue="Churn", bins=30, kde=False, multiple="stack")
plt.title("Tenure Distribution by Churn")
plt.xlabel("Tenure (months)")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

# 5.3 Boxplot – tenure vs churn
plt.figure()
sns.boxplot(data=data, x="Churn", y="tenure")
plt.title("Tenure vs Churn")
plt.xlabel("Churn")
plt.ylabel("Tenure (months)")
plt.tight_layout()
plt.show()

# 5.4 Summary statistics – tenure by churn
tenure_stats = data.groupby("Churn")["tenure"].describe()
print("\nTenure statistics by Churn:")
display(tenure_stats.round(2))

"""# 6. How Churn varies across different Contract Types and Payment methods.



```
6.1 Churn vs Contract Type
6.2 Churn Rate by Contract
6.3 Churn vs Payment Method
6.4 Churn rate by Payment Method
```


"""

# 6.1 Churn vs Contract Type
plt.figure()
sns.countplot(data=data, x="Contract", hue="Churn")
plt.title("Churn by Contract Type – Count")
plt.xlabel("Contract Type")
plt.ylabel("Number of Customers")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

# 6.2 Churn Rate by Contract
churn_by_contract = (
    data.groupby("Contract")["Churn"]
    .value_counts(normalize=True)
    .unstack()
    .rename(columns={"Yes": "Churn_Yes", "No": "Churn_No"}) * 100
)

print("\nChurn rate (%) by Contract type:")
display(churn_by_contract.round(2))
print("\n")


# For clear visualization of churn rate only (Yes)
plt.figure()
sns.barplot(
    x=churn_by_contract.index,
    y=churn_by_contract["Churn_Yes"]
)
plt.title("Churn Rate by Contract Type (%)")
plt.xlabel("Contract Type")
plt.ylabel("Churn Rate (%)")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

# 6.3 Churn vs Payment Method
plt.figure()
sns.countplot(data=data, x="PaymentMethod", hue="Churn")
plt.title("Churn by Payment Method – Count")
plt.xlabel("Payment Method")
plt.ylabel("Number of Customers")
plt.xticks(rotation=20, ha="right")
plt.tight_layout()
plt.show()

# 6.4 Churn rate by Payment Method
churn_by_payment = (
    data.groupby("PaymentMethod")["Churn"]
    .value_counts(normalize=True)
    .unstack()
    .rename(columns={"Yes": "Churn_Yes", "No": "Churn_No"}) * 100
)

print("\nChurn rate (%) by Payment Method:")
display(churn_by_payment.round(2))
print("\n")


# For clear visualization of churn rate only (Yes)
plt.figure()
sns.barplot(
    x=churn_by_payment.index,
    y=churn_by_payment["Churn_Yes"]
)
plt.title("Churn Rate by Payment Method (%)")
plt.xlabel("Payment Method")
plt.ylabel("Churn Rate (%)")
plt.xticks(rotation=20, ha="right")
plt.tight_layout()
plt.show()